# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'flask',
        'waitress',
        'env_loader',
        'flask_app',
        'database',
        'inicio',
        'inicio.utils',
        'inicio.utils.debug',
        'inicio.utils.erro',
        'inicio.rede',
        'inicio.rede.firewall',
        'inicio.rede.porta',
        'inicio.rede.sync',
        'inicio.rede.zeroconf_discovery',
        'zeroconf',
        'inicio.opcoes',
        'inicio.servidores',
        'inicio.servidores.modos',
        'tray_icon',
        'openpyxl',
        'docx',
        'pystray',
        'pystray._win32',
        'pystray._darwin',
        'pystray._xorg',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageTk',
        'dotenv',
        'sqlite3',
        'tkinter',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Gerente',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Sem terminal. build_gerente.py usa True apenas se FLASK_DEBUG=true
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/img/favicon.ico',  # Ícone do executável
)
